"""Unified routing fabric for MPREG."""

from __future__ import annotations

from .cache_federation import (
    CacheDigest,
    CacheDigestEntry,
    CacheOperationMessage,
    CacheOperationType,
    ConflictResolutionStrategy,
    FabricCacheProtocol,
)
from .cache_selection import CachePeerSelector, CacheSelectionWeights
from .cache_transport import (
    CacheMessageKind,
    CacheTransport,
    InProcessCacheTransport,
    ServerCacheTransport,
)
from .catalog import (
    CacheNodeKey,
    CacheNodeProfile,
    CacheRole,
    CacheRoleEntry,
    CacheRoleKey,
    FunctionEndpoint,
    FunctionKey,
    NodeDescriptor,
    NodeKey,
    QueueEndpoint,
    QueueHealth,
    QueueKey,
    RoutingCatalog,
    ServiceEndpoint,
    ServiceKey,
    TopicSubscription,
    TransportEndpoint,
)
from .catalog_delta import RoutingCatalogApplier, RoutingCatalogDelta
from .engine import (
    ClusterRoutePlan,
    ClusterRouteReason,
    FunctionRoutePlan,
    FunctionRouteReason,
    RoutingEngine,
)
from .federation_graph import (
    DijkstraRouter,
    FederationGraph,
    FederationGraphEdge,
    FederationGraphNode,
    GeographicAStarRouter,
    GeographicCoordinate,
    GraphBasedFederationRouter,
    MultiPathRouter,
    NodeType,
)
from .federation_optimized import ClusterIdentity
from .federation_planner import (
    FabricFederationPlanner,
    FabricForwardingFailureReason,
    FabricForwardingPlan,
)
from .hub_registry import (
    ClusterRegistrar,
    HubHealthMonitor,
    HubRegistrationInfo,
    HubRegistry,
)
from .hubs import (
    AggregatedSubscriptionState,
    FederationHub,
    GlobalHub,
    HubCapabilities,
    HubTier,
    HubTopology,
    LocalHub,
    RegionalHub,
    TopicBloomFilter,
)
from .index import (
    CacheProfileQuery,
    CacheQuery,
    FunctionQuery,
    NodeQuery,
    QueueQuery,
    RoutingIndex,
    ServiceQuery,
    TopicQuery,
)
from .link_state import (
    LinkStateAnnouncer,
    LinkStateAreaPair,
    LinkStateAreaPolicy,
    LinkStateMode,
    LinkStateNeighbor,
    LinkStateProcessor,
    LinkStatePublisher,
    LinkStateSummaryFilter,
    LinkStateTable,
    LinkStateUpdate,
)
from .message import (
    DeliveryGuarantee,
    MessageHeaders,
    MessageType,
    RoutingPriority,
    UnifiedMessage,
)
from .message_codec import (
    message_headers_from_dict,
    message_headers_to_dict,
    unified_message_from_dict,
    unified_message_to_dict,
)
from .peer_directory import PeerDirectory, PeerDirectoryDelta, PeerNeighbor
from .pubsub_forwarding import (
    FABRIC_PUBSUB_FORWARDING_KEY,
    PubSubForwardingMetadata,
)
from .raft_messages import (
    RAFT_RPC_REQUEST_KIND,
    RAFT_RPC_RESPONSE_KIND,
    RAFT_RPC_TOPIC,
    FabricRaftRpcRequest,
    FabricRaftRpcResponse,
    RaftRpcKind,
)
from .raft_transport import (
    FabricRaftTransport,
    FabricRaftTransportConfig,
    FabricRaftTransportHooks,
)
from .route_announcer import (
    RouteAnnouncementProcessor,
    RouteAnnouncementPublisher,
    RouteAnnouncer,
    RouteLinkMetrics,
)
from .route_control import (
    RouteAnnouncement,
    RouteBestKey,
    RouteCandidateTrace,
    RouteControlStats,
    RouteConvergenceState,
    RouteDestination,
    RouteFlapState,
    RouteHoldDownKey,
    RouteMetrics,
    RoutePath,
    RoutePolicy,
    RouteRecord,
    RouteSelectionTrace,
    RouteStabilityPolicy,
    RouteTable,
    RouteTiebreaker,
    RouteWithdrawal,
)
from .route_key_gossip import RouteKeyAnnouncer, RouteKeyProcessor
from .route_keys import (
    RouteKeyAnnouncement,
    RouteKeyProvider,
    RouteKeyRecord,
    RouteKeyRegistry,
    RouteKeySet,
    refresh_route_keys,
)
from .route_policy_directory import RouteNeighborPolicy, RoutePolicyDirectory
from .route_security import (
    RouteAnnouncementSigner,
    RouteSecurityConfig,
)
from .route_withdrawal import RouteWithdrawalCoordinator
from .router import (
    FabricRouter,
    FabricRouteResult,
    FabricRouteTarget,
    FabricRoutingConfig,
    FabricRoutingPolicy,
    FabricRoutingStatisticsSnapshot,
    RouteHandlerRegistry,
    RoutingMetrics,
    create_correlation_id,
    create_fabric_router,
    create_route_id,
    extract_system_from_topic,
    is_control_plane_message,
    is_federation_message,
    is_internal_topic,
)
from .rpc_messages import (
    FABRIC_RPC_REQUEST_KIND,
    FABRIC_RPC_RESPONSE_KIND,
    FabricRPCRequest,
    FabricRPCResponse,
)
from .server_transport import ServerFabricTransport

__all__ = [
    "FABRIC_PUBSUB_FORWARDING_KEY",
    "FABRIC_RPC_REQUEST_KIND",
    "FABRIC_RPC_RESPONSE_KIND",
    "RAFT_RPC_REQUEST_KIND",
    "RAFT_RPC_RESPONSE_KIND",
    "RAFT_RPC_TOPIC",
    "AggregatedSubscriptionState",
    "CacheDigest",
    "CacheDigestEntry",
    "CacheMessageKind",
    "CacheNodeKey",
    "CacheNodeProfile",
    "CacheOperationMessage",
    "CacheOperationType",
    "CachePeerSelector",
    "CacheProfileQuery",
    "CacheQuery",
    "CacheRole",
    "CacheRoleEntry",
    "CacheRoleKey",
    "CacheSelectionWeights",
    "CacheTransport",
    "ClusterIdentity",
    "ClusterRegistrar",
    "ClusterRoutePlan",
    "ClusterRouteReason",
    "ConflictResolutionStrategy",
    "DeliveryGuarantee",
    "DijkstraRouter",
    "FabricCacheProtocol",
    "FabricFederationPlanner",
    "FabricForwardingFailureReason",
    "FabricForwardingPlan",
    "FabricRPCRequest",
    "FabricRPCResponse",
    "FabricRaftRpcRequest",
    "FabricRaftRpcResponse",
    "FabricRaftTransport",
    "FabricRaftTransportConfig",
    "FabricRaftTransportHooks",
    "FabricRouteResult",
    "FabricRouteTarget",
    "FabricRouter",
    "FabricRoutingConfig",
    "FabricRoutingPolicy",
    "FabricRoutingStatisticsSnapshot",
    "FederationGraph",
    "FederationGraphEdge",
    "FederationGraphNode",
    "FederationHub",
    "FunctionEndpoint",
    "FunctionKey",
    "FunctionQuery",
    "FunctionRoutePlan",
    "FunctionRouteReason",
    "GeographicAStarRouter",
    "GeographicCoordinate",
    "GlobalHub",
    "GraphBasedFederationRouter",
    "HubCapabilities",
    "HubHealthMonitor",
    "HubRegistrationInfo",
    "HubRegistry",
    "HubTier",
    "HubTopology",
    "InProcessCacheTransport",
    "LinkStateAnnouncer",
    "LinkStateAreaPair",
    "LinkStateAreaPolicy",
    "LinkStateMode",
    "LinkStateNeighbor",
    "LinkStateProcessor",
    "LinkStatePublisher",
    "LinkStateSummaryFilter",
    "LinkStateTable",
    "LinkStateUpdate",
    "LocalHub",
    "MessageHeaders",
    "MessageType",
    "MultiPathRouter",
    "NodeDescriptor",
    "NodeKey",
    "NodeQuery",
    "NodeType",
    "PeerDirectory",
    "PeerDirectoryDelta",
    "PeerNeighbor",
    "PubSubForwardingMetadata",
    "QueueEndpoint",
    "QueueHealth",
    "QueueKey",
    "QueueQuery",
    "RaftRpcKind",
    "RegionalHub",
    "RouteAnnouncement",
    "RouteAnnouncementProcessor",
    "RouteAnnouncementPublisher",
    "RouteAnnouncementSigner",
    "RouteAnnouncer",
    "RouteBestKey",
    "RouteCandidateTrace",
    "RouteControlStats",
    "RouteConvergenceState",
    "RouteDestination",
    "RouteFlapState",
    "RouteHandlerRegistry",
    "RouteHoldDownKey",
    "RouteKeyAnnouncement",
    "RouteKeyAnnouncer",
    "RouteKeyProcessor",
    "RouteKeyProvider",
    "RouteKeyRecord",
    "RouteKeyRegistry",
    "RouteKeySet",
    "RouteLinkMetrics",
    "RouteMetrics",
    "RouteNeighborPolicy",
    "RoutePath",
    "RoutePolicy",
    "RoutePolicyDirectory",
    "RouteRecord",
    "RouteSecurityConfig",
    "RouteSelectionTrace",
    "RouteStabilityPolicy",
    "RouteTable",
    "RouteTiebreaker",
    "RouteWithdrawal",
    "RouteWithdrawalCoordinator",
    "RoutingCatalog",
    "RoutingCatalogApplier",
    "RoutingCatalogDelta",
    "RoutingEngine",
    "RoutingIndex",
    "RoutingMetrics",
    "RoutingPriority",
    "ServerCacheTransport",
    "ServerFabricTransport",
    "ServiceEndpoint",
    "ServiceKey",
    "ServiceQuery",
    "TopicBloomFilter",
    "TopicQuery",
    "TopicSubscription",
    "TransportEndpoint",
    "UnifiedMessage",
    "create_correlation_id",
    "create_fabric_router",
    "create_route_id",
    "extract_system_from_topic",
    "is_control_plane_message",
    "is_federation_message",
    "is_internal_topic",
    "message_headers_from_dict",
    "message_headers_to_dict",
    "refresh_route_keys",
    "unified_message_from_dict",
    "unified_message_to_dict",
]
